import mongoose from 'mongoose';
import dotenv from 'dotenv';
import List from '../models/List';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/listgame';

const spotifyTop100 = {
  slug: 'spotify-top-100',
  title: 'Top 100 Most Streamed Spotify Songs of All Time',
  category: 'Music',
  description: 'The 100 most-streamed songs in Spotify history. Rank 1 = most streamed, Rank 100 = fewest streams but worth the most points!',
  items: [
    { rank: 1, value: 'Blinding Lights', hint: 'The Weeknd' },
    { rank: 2, value: 'Shape of You', hint: 'Ed Sheeran' },
    { rank: 3, value: 'Someone You Loved', hint: 'Lewis Capaldi' },
    { rank: 4, value: 'Dance Monkey', hint: 'Tones and I' },
    { rank: 5, value: 'Sunflower', hint: 'Post Malone & Swae Lee' },
    { rank: 6, value: 'One Dance', hint: 'Drake' },
    { rank: 7, value: 'Stay', hint: 'The Kid LAROI & Justin Bieber' },
    { rank: 8, value: 'Rockstar', hint: 'Post Malone ft. 21 Savage' },
    { rank: 9, value: 'Believer', hint: 'Imagine Dragons' },
    { rank: 10, value: 'Closer', hint: 'The Chainsmokers ft. Halsey' },
    { rank: 11, value: 'Thinking Out Loud', hint: 'Ed Sheeran' },
    { rank: 12, value: 'God\'s Plan', hint: 'Drake' },
    { rank: 13, value: 'Perfect', hint: 'Ed Sheeran' },
    { rank: 14, value: 'Señorita', hint: 'Shawn Mendes & Camila Cabello' },
    { rank: 15, value: 'Photograph', hint: 'Ed Sheeran' },
    { rank: 16, value: 'Lucid Dreams', hint: 'Juice WRLD' },
    { rank: 17, value: 'Bad Guy', hint: 'Billie Eilish' },
    { rank: 18, value: 'Watermelon Sugar', hint: 'Harry Styles' },
    { rank: 19, value: 'Shallow', hint: 'Lady Gaga & Bradley Cooper' },
    { rank: 20, value: 'Circles', hint: 'Post Malone' },
    { rank: 21, value: 'Don\'t Start Now', hint: 'Dua Lipa' },
    { rank: 22, value: 'Levitating', hint: 'Dua Lipa ft. DaBaby' },
    { rank: 23, value: 'Happier', hint: 'Marshmello & Bastille' },
    { rank: 24, value: 'Intention', hint: 'Justin Bieber ft. Quavo' },
    { rank: 25, value: 'Heat Waves', hint: 'Glass Animals' },
    { rank: 26, value: 'Peaches', hint: 'Justin Bieber ft. Daniel Caesar & Giveon' },
    { rank: 27, value: 'drivers license', hint: 'Olivia Rodrigo' },
    { rank: 28, value: 'Save Your Tears', hint: 'The Weeknd' },
    { rank: 29, value: 'Lose Yourself', hint: 'Eminem' },
    { rank: 30, value: 'In My Feelings', hint: 'Drake' },
    { rank: 31, value: 'Memories', hint: 'Maroon 5' },
    { rank: 32, value: 'Uptown Funk', hint: 'Mark Ronson ft. Bruno Mars' },
    { rank: 33, value: 'Havana', hint: 'Camila Cabello ft. Young Thug' },
    { rank: 34, value: 'Lean On', hint: 'Major Lazer & DJ Snake ft. MO' },
    { rank: 35, value: 'Sorry', hint: 'Justin Bieber' },
    { rank: 36, value: 'Love Yourself', hint: 'Justin Bieber' },
    { rank: 37, value: 'Wolves', hint: 'Marshmello & Khalid' },
    { rank: 38, value: 'Counting Stars', hint: 'OneRepublic' },
    { rank: 39, value: 'Stressed Out', hint: 'Twenty One Pilots' },
    { rank: 40, value: 'Something Just Like This', hint: 'The Chainsmokers & Coldplay' },
    { rank: 41, value: 'Ride', hint: 'Twenty One Pilots' },
    { rank: 42, value: 'Let Her Go', hint: 'Passenger' },
    { rank: 43, value: 'Happier', hint: 'Olivia Rodrigo' },
    { rank: 44, value: 'Thunder', hint: 'Imagine Dragons' },
    { rank: 45, value: 'Riptide', hint: 'Vance Joy' },
    { rank: 46, value: 'SugarCrash!', hint: 'ElyOtto' },
    { rank: 47, value: 'Good 4 U', hint: 'Olivia Rodrigo' },
    { rank: 48, value: 'Demons', hint: 'Imagine Dragons' },
    { rank: 49, value: 'Starboy', hint: 'The Weeknd ft. Daft Punk' },
    { rank: 50, value: 'Can\'t Feel My Face', hint: 'The Weeknd' },
    { rank: 51, value: 'Radioactive', hint: 'Imagine Dragons' },
    { rank: 52, value: 'Sad!', hint: 'XXXTENTACION' },
    { rank: 53, value: 'Take Me to Church', hint: 'Hozier' },
    { rank: 54, value: 'Love Me Like You Do', hint: 'Ellie Goulding' },
    { rank: 55, value: 'Cheap Thrills', hint: 'Sia ft. Sean Paul' },
    { rank: 56, value: 'Boom Boom Boom', hint: 'will.i.am & Daddy Yankee' },
    { rank: 57, value: 'Wake Me Up', hint: 'Avicii' },
    { rank: 58, value: 'I Will Always Love You', hint: 'Whitney Houston' },
    { rank: 59, value: 'Bohemian Rhapsody', hint: 'Queen' },
    { rank: 60, value: 'Hotel California', hint: 'Eagles' },
    { rank: 61, value: 'Despacito', hint: 'Luis Fonsi ft. Daddy Yankee' },
    { rank: 62, value: 'Mi Gente', hint: 'J Balvin & Willy William' },
    { rank: 63, value: 'Taki Taki', hint: 'DJ Snake ft. Selena Gomez & Ozuna' },
    { rank: 64, value: 'Happier Than Ever', hint: 'Billie Eilish' },
    { rank: 65, value: 'Therefore I Am', hint: 'Billie Eilish' },
    { rank: 66, value: 'Enemy', hint: 'Imagine Dragons & Arcane' },
    { rank: 67, value: 'Industry Baby', hint: 'Lil Nas X & Jack Harlow' },
    { rank: 68, value: 'Montero', hint: 'Lil Nas X' },
    { rank: 69, value: 'Old Town Road', hint: 'Lil Nas X ft. Billy Ray Cyrus' },
    { rank: 70, value: 'Without Me', hint: 'Halsey' },
    { rank: 71, value: 'Positions', hint: 'Ariana Grande' },
    { rank: 72, value: '7 Rings', hint: 'Ariana Grande' },
    { rank: 73, value: 'Thank U, Next', hint: 'Ariana Grande' },
    { rank: 74, value: 'Break My Heart', hint: 'Dua Lipa' },
    { rank: 75, value: 'Physical', hint: 'Dua Lipa' },
    { rank: 76, value: 'Future Nostalgia', hint: 'Dua Lipa' },
    { rank: 77, value: 'Midnight Rain', hint: 'Taylor Swift' },
    { rank: 78, value: 'Anti-Hero', hint: 'Taylor Swift' },
    { rank: 79, value: 'Shake It Off', hint: 'Taylor Swift' },
    { rank: 80, value: 'Blank Space', hint: 'Taylor Swift' },
    { rank: 81, value: 'Style', hint: 'Taylor Swift' },
    { rank: 82, value: 'As It Was', hint: 'Harry Styles' },
    { rank: 83, value: 'Golden', hint: 'Harry Styles' },
    { rank: 84, value: 'Adore You', hint: 'Harry Styles' },
    { rank: 85, value: 'Chandelier', hint: 'Sia' },
    { rank: 86, value: 'Elastic Heart', hint: 'Sia' },
    { rank: 87, value: 'Rolling in the Deep', hint: 'Adele' },
    { rank: 88, value: 'Someone Like You', hint: 'Adele' },
    { rank: 89, value: 'Hello', hint: 'Adele' },
    { rank: 90, value: 'Easy On Me', hint: 'Adele' },
    { rank: 91, value: 'Smells Like Teen Spirit', hint: 'Nirvana' },
    { rank: 92, value: 'Mr. Brightside', hint: 'The Killers' },
    { rank: 93, value: 'Seven Nation Army', hint: 'The White Stripes' },
    { rank: 94, value: 'Eye of the Tiger', hint: 'Survivor' },
    { rank: 95, value: 'Don\'t Stop Believin\'', hint: 'Journey' },
    { rank: 96, value: 'Sweet Child O\' Mine', hint: 'Guns N\' Roses' },
    { rank: 97, value: 'Africa', hint: 'Toto' },
    { rank: 98, value: 'Take On Me', hint: 'a-ha' },
    { rank: 99, value: 'Livin\' on a Prayer', hint: 'Bon Jovi' },
    { rank: 100, value: 'Numb', hint: 'Linkin Park' },
  ],
};

const boxOfficeTop100 = {
  slug: 'box-office-top-100',
  title: 'Top 100 Highest-Grossing Movies of All Time (Worldwide Box Office)',
  category: 'Movies',
  description: 'The 100 highest-grossing films worldwide. Rank 1 = highest grossing, Rank 100 = lowest on the list but worth the most points!',
  items: [
    { rank: 1, value: 'Avatar', hint: '2009' },
    { rank: 2, value: 'Avengers: Endgame', hint: '2019' },
    { rank: 3, value: 'Titanic', hint: '1997' },
    { rank: 4, value: 'Star Wars: The Force Awakens', hint: '2015' },
    { rank: 5, value: 'Avengers: Infinity War', hint: '2018' },
    { rank: 6, value: 'Spider-Man: No Way Home', hint: '2021' },
    { rank: 7, value: 'Jurassic World', hint: '2015' },
    { rank: 8, value: 'The Lion King', hint: '2019' },
    { rank: 9, value: 'The Avengers', hint: '2012' },
    { rank: 10, value: 'Furious 7', hint: '2015' },
    { rank: 11, value: 'Top Gun: Maverick', hint: '2022' },
    { rank: 12, value: 'Frozen II', hint: '2019' },
    { rank: 13, value: 'Avengers: Age of Ultron', hint: '2015' },
    { rank: 14, value: 'The Dark Knight Rises', hint: '2012' },
    { rank: 15, value: 'Incredibles 2', hint: '2018' },
    { rank: 16, value: 'The Fate of the Furious', hint: '2017' },
    { rank: 17, value: 'Iron Man 3', hint: '2013' },
    { rank: 18, value: 'Minions', hint: '2015' },
    { rank: 19, value: 'Captain America: Civil War', hint: '2016' },
    { rank: 20, value: 'Aquaman', hint: '2018' },
    { rank: 21, value: 'The Lord of the Rings: The Return of the King', hint: '2003' },
    { rank: 22, value: 'Transformers: Dark of the Moon', hint: '2011' },
    { rank: 23, value: 'Skyfall', hint: '2012' },
    { rank: 24, value: 'Transformers: Age of Extinction', hint: '2014' },
    { rank: 25, value: 'The Dark Knight', hint: '2008' },
    { rank: 26, value: 'Toy Story 4', hint: '2019' },
    { rank: 27, value: 'Toy Story 3', hint: '2010' },
    { rank: 28, value: 'Pirates of the Caribbean: Dead Man\'s Chest', hint: '2006' },
    { rank: 29, value: 'Rogue One: A Star Wars Story', hint: '2016' },
    { rank: 30, value: 'Aladdin', hint: '2019' },
    { rank: 31, value: 'Finding Dory', hint: '2016' },
    { rank: 32, value: 'Alice in Wonderland', hint: '2010' },
    { rank: 33, value: 'Zootopia', hint: '2016' },
    { rank: 34, value: 'The Hunger Games: Catching Fire', hint: '2013' },
    { rank: 35, value: 'Harry Potter and the Deathly Hallows Part 2', hint: '2011' },
    { rank: 36, value: 'The Amazing Spider-Man 2', hint: '2014' },
    { rank: 37, value: 'Batman v Superman: Dawn of Justice', hint: '2016' },
    { rank: 38, value: 'Pirates of the Caribbean: On Stranger Tides', hint: '2011' },
    { rank: 39, value: 'Jurassic World: Fallen Kingdom', hint: '2018' },
    { rank: 40, value: 'Frozen', hint: '2013' },
    { rank: 41, value: 'Beauty and the Beast', hint: '2017' },
    { rank: 42, value: 'Wonder Woman', hint: '2017' },
    { rank: 43, value: 'Coco', hint: '2017' },
    { rank: 44, value: 'Black Panther', hint: '2018' },
    { rank: 45, value: 'Harry Potter and the Sorcerer\'s Stone', hint: '2001' },
    { rank: 46, value: 'Despicable Me 3', hint: '2017' },
    { rank: 47, value: 'The Jungle Book', hint: '2016' },
    { rank: 48, value: 'Fast Five', hint: '2011' },
    { rank: 49, value: 'Jumanji: Welcome to the Jungle', hint: '2017' },
    { rank: 50, value: 'Doctor Strange in the Multiverse of Madness', hint: '2022' },
    { rank: 51, value: 'Guardians of the Galaxy Vol. 2', hint: '2017' },
    { rank: 52, value: 'Transformers: Revenge of the Fallen', hint: '2009' },
    { rank: 53, value: 'Thor: Ragnarok', hint: '2017' },
    { rank: 54, value: 'Spider-Man: Far From Home', hint: '2019' },
    { rank: 55, value: 'Moana', hint: '2016' },
    { rank: 56, value: 'Despicable Me 2', hint: '2013' },
    { rank: 57, value: 'The Hobbit: An Unexpected Journey', hint: '2012' },
    { rank: 58, value: 'Finding Nemo', hint: '2003' },
    { rank: 59, value: 'Ice Age: Continental Drift', hint: '2012' },
    { rank: 60, value: 'Shrek 2', hint: '2004' },
    { rank: 61, value: 'Harry Potter and the Deathly Hallows Part 1', hint: '2010' },
    { rank: 62, value: 'Mission: Impossible – Fallout', hint: '2018' },
    { rank: 63, value: 'Thor: Love and Thunder', hint: '2022' },
    { rank: 64, value: 'Mamma Mia!', hint: '2008' },
    { rank: 65, value: 'Captain Marvel', hint: '2019' },
    { rank: 66, value: 'Pirates of the Caribbean: At World\'s End', hint: '2007' },
    { rank: 67, value: 'Ant-Man and the Wasp', hint: '2018' },
    { rank: 68, value: 'Harry Potter and the Order of the Phoenix', hint: '2007' },
    { rank: 69, value: 'The Hobbit: The Desolation of Smaug', hint: '2013' },
    { rank: 70, value: 'The Twilight Saga: Breaking Dawn Part 2', hint: '2012' },
    { rank: 71, value: 'Inception', hint: '2010' },
    { rank: 72, value: 'Men in Black 3', hint: '2012' },
    { rank: 73, value: 'The Hobbit: The Battle of the Five Armies', hint: '2014' },
    { rank: 74, value: 'Harry Potter and the Half-Blood Prince', hint: '2009' },
    { rank: 75, value: 'The Lord of the Rings: The Two Towers', hint: '2002' },
    { rank: 76, value: 'Superman Returns', hint: '2006' },
    { rank: 77, value: 'The Hobbit: An Unexpected Journey', hint: '2012 extended' },
    { rank: 78, value: 'Warcraft', hint: '2016' },
    { rank: 79, value: 'Harry Potter and the Goblet of Fire', hint: '2005' },
    { rank: 80, value: 'Spider-Man 3', hint: '2007' },
    { rank: 81, value: 'Ice Age: Dawn of the Dinosaurs', hint: '2009' },
    { rank: 82, value: 'Harry Potter and the Chamber of Secrets', hint: '2002' },
    { rank: 83, value: 'The Lord of the Rings: The Fellowship of the Ring', hint: '2001' },
    { rank: 84, value: 'The Amazing Spider-Man', hint: '2012' },
    { rank: 85, value: 'Shrek Forever After', hint: '2010' },
    { rank: 86, value: 'Batman v Superman', hint: '2016' },
    { rank: 87, value: 'Fast & Furious 6', hint: '2013' },
    { rank: 88, value: 'Kung Fu Panda 2', hint: '2011' },
    { rank: 89, value: 'Madagascar 3: Europe\'s Most Wanted', hint: '2012' },
    { rank: 90, value: 'Maleficent', hint: '2014' },
    { rank: 91, value: 'Ice Age: The Meltdown', hint: '2006' },
    { rank: 92, value: 'The Twilight Saga: New Moon', hint: '2009' },
    { rank: 93, value: 'Indiana Jones and the Kingdom of the Crystal Skull', hint: '2008' },
    { rank: 94, value: 'Mission: Impossible – Ghost Protocol', hint: '2011' },
    { rank: 95, value: 'The Matrix Reloaded', hint: '2003' },
    { rank: 96, value: 'Shrek the Third', hint: '2007' },
    { rank: 97, value: 'Up', hint: '2009' },
    { rank: 98, value: 'Wall-E', hint: '2008' },
    { rank: 99, value: 'The Twilight Saga: Eclipse', hint: '2010' },
    { rank: 100, value: 'Spectre', hint: '2015' },
  ],
};

const akcDogBreeds2023 = {
  slug: 'akc-dog-breeds-2023',
  title: 'Top 100 Most Popular Dog Breeds (AKC 2023 Rankings)',
  category: 'Animals',
  description: 'The 100 most popular dog breeds according to the American Kennel Club\'s 2023 registration statistics. Rank 1 = most popular!',
  items: [
    { rank: 1, value: 'French Bulldog', hint: 'AKC #1 2023' },
    { rank: 2, value: 'Labrador Retriever', hint: 'AKC #2 2023' },
    { rank: 3, value: 'Golden Retriever', hint: 'AKC #3 2023' },
    { rank: 4, value: 'German Shepherd', hint: 'AKC #4 2023' },
    { rank: 5, value: 'Bulldog', hint: 'AKC #5 2023' },
    { rank: 6, value: 'Poodle', hint: 'AKC #6 2023' },
    { rank: 7, value: 'Rottweiler', hint: 'AKC #7 2023' },
    { rank: 8, value: 'Beagle', hint: 'AKC #8 2023' },
    { rank: 9, value: 'German Shorthaired Pointer', hint: 'AKC #9 2023' },
    { rank: 10, value: 'Dachshund', hint: 'AKC #10 2023' },
    { rank: 11, value: 'Pembroke Welsh Corgi', hint: 'AKC #11 2023' },
    { rank: 12, value: 'Australian Shepherd', hint: 'AKC #12 2023' },
    { rank: 13, value: 'Yorkshire Terrier', hint: 'AKC #13 2023' },
    { rank: 14, value: 'Cavalier King Charles Spaniel', hint: 'AKC #14 2023' },
    { rank: 15, value: 'Doberman Pinscher', hint: 'AKC #15 2023' },
    { rank: 16, value: 'Boxer', hint: 'AKC #16 2023' },
    { rank: 17, value: 'Miniature Schnauzer', hint: 'AKC #17 2023' },
    { rank: 18, value: 'Cane Corso', hint: 'AKC #18 2023' },
    { rank: 19, value: 'Great Dane', hint: 'AKC #19 2023' },
    { rank: 20, value: 'Shih Tzu', hint: 'AKC #20 2023' },
    { rank: 21, value: 'Siberian Husky', hint: 'AKC #21 2023' },
    { rank: 22, value: 'Bernese Mountain Dog', hint: 'AKC #22 2023' },
    { rank: 23, value: 'Pomeranian', hint: 'AKC #23 2023' },
    { rank: 24, value: 'Boston Terrier', hint: 'AKC #24 2023' },
    { rank: 25, value: 'Havanese', hint: 'AKC #25 2023' },
    { rank: 26, value: 'Shetland Sheepdog', hint: 'AKC #26 2023' },
    { rank: 27, value: 'Brittany', hint: 'AKC #27 2023' },
    { rank: 28, value: 'English Springer Spaniel', hint: 'AKC #28 2023' },
    { rank: 29, value: 'Pug', hint: 'AKC #29 2023' },
    { rank: 30, value: 'Pointer', hint: 'AKC #30 2023' },
    { rank: 31, value: 'Border Collie', hint: 'AKC #31 2023' },
    { rank: 32, value: 'Belgian Malinois', hint: 'AKC #32 2023' },
    { rank: 33, value: 'Mastiff', hint: 'AKC #33 2023' },
    { rank: 34, value: 'Cocker Spaniel', hint: 'AKC #34 2023' },
    { rank: 35, value: 'Miniature American Shepherd', hint: 'AKC #35 2023' },
    { rank: 36, value: 'Vizsla', hint: 'AKC #36 2023' },
    { rank: 37, value: 'Weimaraner', hint: 'AKC #37 2023' },
    { rank: 38, value: 'Collie', hint: 'AKC #38 2023' },
    { rank: 39, value: 'Newfoundland', hint: 'AKC #39 2023' },
    { rank: 40, value: 'West Highland White Terrier', hint: 'AKC #40 2023' },
    { rank: 41, value: 'Bichon Frise', hint: 'AKC #41 2023' },
    { rank: 42, value: 'Rhodesian Ridgeback', hint: 'AKC #42 2023' },
    { rank: 43, value: 'Shiba Inu', hint: 'AKC #43 2023' },
    { rank: 44, value: 'Belgian Tervuren', hint: 'AKC #44 2023' },
    { rank: 45, value: 'Chesapeake Bay Retriever', hint: 'AKC #45 2023' },
    { rank: 46, value: 'Maltese', hint: 'AKC #46 2023' },
    { rank: 47, value: 'Basset Hound', hint: 'AKC #47 2023' },
    { rank: 48, value: 'Akita', hint: 'AKC #48 2023' },
    { rank: 49, value: 'Chihuahua', hint: 'AKC #49 2023' },
    { rank: 50, value: 'Bloodhound', hint: 'AKC #50 2023' },
    { rank: 51, value: 'Portuguese Water Dog', hint: 'AKC #51 2023' },
    { rank: 52, value: 'Flat-Coated Retriever', hint: 'AKC #52 2023' },
    { rank: 53, value: 'English Setter', hint: 'AKC #53 2023' },
    { rank: 54, value: 'Alaskan Malamute', hint: 'AKC #54 2023' },
    { rank: 55, value: 'Lhasa Apso', hint: 'AKC #55 2023' },
    { rank: 56, value: 'Scottish Terrier', hint: 'AKC #56 2023' },
    { rank: 57, value: 'German Wirehaired Pointer', hint: 'AKC #57 2023' },
    { rank: 58, value: 'Saint Bernard', hint: 'AKC #58 2023' },
    { rank: 59, value: 'Bull Terrier', hint: 'AKC #59 2023' },
    { rank: 60, value: 'Soft Coated Wheaten Terrier', hint: 'AKC #60 2023' },
    { rank: 61, value: 'Gordon Setter', hint: 'AKC #61 2023' },
    { rank: 62, value: 'Wirehaired Pointing Griffon', hint: 'AKC #62 2023' },
    { rank: 63, value: 'Chinese Shar-Pei', hint: 'AKC #63 2023' },
    { rank: 64, value: 'Bouvier des Flandres', hint: 'AKC #64 2023' },
    { rank: 65, value: 'Dalmatian', hint: 'AKC #65 2023' },
    { rank: 66, value: 'Norwegian Elkhound', hint: 'AKC #66 2023' },
    { rank: 67, value: 'Cardigan Welsh Corgi', hint: 'AKC #67 2023' },
    { rank: 68, value: 'Irish Setter', hint: 'AKC #68 2023' },
    { rank: 69, value: 'Greater Swiss Mountain Dog', hint: 'AKC #69 2023' },
    { rank: 70, value: 'American Staffordshire Terrier', hint: 'AKC #70 2023' },
    { rank: 71, value: 'Staffordshire Bull Terrier', hint: 'AKC #71 2023' },
    { rank: 72, value: 'Italian Greyhound', hint: 'AKC #72 2023' },
    { rank: 73, value: 'Cairn Terrier', hint: 'AKC #73 2023' },
    { rank: 74, value: 'Papillon', hint: 'AKC #74 2023' },
    { rank: 75, value: 'Boerboel', hint: 'AKC #75 2023' },
    { rank: 76, value: 'Basenji', hint: 'AKC #76 2023' },
    { rank: 77, value: 'Standard Schnauzer', hint: 'AKC #77 2023' },
    { rank: 78, value: 'Samoyed', hint: 'AKC #78 2023' },
    { rank: 79, value: 'Miniature Pinscher', hint: 'AKC #79 2023' },
    { rank: 80, value: 'Pekingese', hint: 'AKC #80 2023' },
    { rank: 81, value: 'Irish Wolfhound', hint: 'AKC #81 2023' },
    { rank: 82, value: 'Keeshond', hint: 'AKC #82 2023' },
    { rank: 83, value: 'Borzoi', hint: 'AKC #83 2023' },
    { rank: 84, value: 'Coton de Tulear', hint: 'AKC #84 2023' },
    { rank: 85, value: 'Anatolian Shepherd Dog', hint: 'AKC #85 2023' },
    { rank: 86, value: 'Leonberger', hint: 'AKC #86 2023' },
    { rank: 87, value: 'Finnish Spitz', hint: 'AKC #87 2023' },
    { rank: 88, value: 'Black and Tan Coonhound', hint: 'AKC #88 2023' },
    { rank: 89, value: 'Tibetan Mastiff', hint: 'AKC #89 2023' },
    { rank: 90, value: 'Lagotto Romagnolo', hint: 'AKC #90 2023' },
    { rank: 91, value: 'Swedish Vallhund', hint: 'AKC #91 2023' },
    { rank: 92, value: 'American English Coonhound', hint: 'AKC #92 2023' },
    { rank: 93, value: 'Bracco Italiano', hint: 'AKC #93 2023' },
    { rank: 94, value: 'Bergamasco Sheepdog', hint: 'AKC #94 2023' },
    { rank: 95, value: 'Spinone Italiano', hint: 'AKC #95 2023' },
    { rank: 96, value: 'Azawakh', hint: 'AKC #96 2023' },
    { rank: 97, value: 'Sloughi', hint: 'AKC #97 2023' },
    { rank: 98, value: 'Nederlandse Kooikerhondje', hint: 'AKC #98 2023' },
    { rank: 99, value: 'Barbet', hint: 'AKC #99 2023' },
    { rank: 100, value: 'Mudi', hint: 'AKC #100 2023' },
  ],
};

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await List.deleteMany({});
    console.log('Cleared existing lists');

    // Insert new data
    await List.insertMany([spotifyTop100, boxOfficeTop100, akcDogBreeds2023]);
    console.log('Seeded 3 lists successfully');

    await mongoose.disconnect();
    console.log('Done!');
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err);
    process.exit(1);
  }
}

seed();
